= Pages

Each AsciiDoc file (unless being an <<02-includes.adoc#, included file>>) will result in a separate Confluence page and
must contain a top-level document title which will be used as the Confluence page title:

[listing]
....
= Document Title
....

According to the restrictions of Confluence, document titles must be unique within the Confluence space the
documentation is published to. The AsciiDoc file name itself is not reflected in Confluence.


== Keywords / Labels

AsciiDoc keywords defined using the `:keywords` attribute as page metadata are automatically added as labels to the
corresponding Confluence page:

[listing]
....
:keywords: label-one, label-two
....


== Links between Pages

Links between pages in Confluence are supported using AsciiDoc inter-document cross references. Target pages are
referenced via the path to the corresponding AsciiDoc file. Paths are resolved relative to the location of the
referencing AsciiDoc file. All referenced AsciiDoc files must be placed below the documentation root folder.

[listing]
....
<<01-pages.adoc#, Link to Pages>>
<<../00-index/06-images.adoc#, Link to Images>>
....

<<01-pages.adoc#, Link to Pages>>
<<../00-index/06-images.adoc#, Link to Images>>


== Links within Pages

Links to content blocks within the same page are supported using AsciiDoc inline anchors and internal cross references:

[listing]
....
[[paragraph-a]]Paragraph with inline anchor

Another paragraph with internal cross-reference to <<paragraph-a>>
....

[[paragraph-a]]Paragraph with inline anchor

Another paragraph with internal cross-reference to <<paragraph-a>>

Links to sections within the same page are supported either using anchors or custom section ids:

[listing]
....
[[section-a]]
=== Section with Anchor

Paragraph with internal cross-reference to <<section-a>>
....

[[section-a]]
=== Section with Anchor

Paragraph with internal cross-reference to <<section-a>>

[listing]
....
[#section-b]
=== Section with Custom Id

Paragraph with internal cross-reference to <<section-b>>
....

[#section-b]
=== Section with Custom Id

Paragraph with internal cross-reference to <<section-b>>


[WARNING]
====
Links from one page to an inline anchor within another page are currently not supported.
====