= Sections

AsciiDoc sections are translated to the corresponding Confluence heading:

[listing]
....
== Section Level 1
....

== Section Level 1


[listing]
....
=== Section Level 2
....

=== Section Level 2


[listing]
....
==== Section Level 3
....

==== Section Level 3


[listing]
....
===== Section Level 4
....

===== Section Level 4


[listing]
....
====== Section Level 5
....

====== Section Level 5

== Alignment of Sections

Alignment (right, left, center, or justify) of sections is supported via the `.text-<alignment>` role:

[listing]
....
[.text-right]
=== This section is right aligned.
....

[.text-right]
=== This section is right aligned.

[listing]
....
[.text-left]
=== This section is left aligned.
....

[.text-left]
=== This section is left aligned.

[listing]
....
[.text-center]
=== This section is center aligned.
....

[.text-center]
=== This section is center aligned.

[listing]
....
[.text-justify]
=== This section with a very, very, very, very, very, very, very, very, very, very, very, very, very, really very long text is justify aligned.
....

[.text-justify]
=== This section with a very, very, very, very, very, very, very, very, very, very, very, very, very, really very long text is justify aligned.
