= Paragraphs

AsciiDoc paragraphs are translated to Confluence paragraphs, supporting all typical styles, for example:

[listing]
....
This is a paragraph with *bold* text.
....

This is a paragraph with *bold* text.


[listing]
....
This is a paragraph with _italic_ text.
....
This is a paragraph with _italic_ text.


[listing]
....
This is a paragraph with `monospaced` text.
....
This is a paragraph with `monospaced` text.


[listing]
....
This is a paragraph with `*_monospaced bold italic_*` text.
....

This is a paragraph with `*_monospaced bold italic_*` text.


[listing]
....
This is a paragraph with ^super^script and ~sub~script text.
....
This is a paragraph with ^super^script and ~sub~script text.

[listing]
....
.This the title of a paragraph
The title of a paragraph will rendered using a custom CSS class `cp-paragraph-title`
....

.This the title of a paragraph
The title of a paragraph will rendered using a custom CSS class `cp-paragraph-title`


== Align text in paragraph 

The name of the role follows the pattern text-<alignment>, where <alignment> is one of left, center, right, or justify (e.g., text-center).

.Example Assign text-center to a paragraph
[listing]
....
[.text-center]
This text is centered, so it must be important.
....

[.text-center]
This text is centered, so it must be important.