= Listings

AsciiDoc literal blocks, listing blocks and code blocks are converted to formatted blocks in Confluence.

A title can be set for each type of block. The title is rendered as the title of confluence panel.

== Literal Block

Literal blocks are converted as pre-formatted text.

----
....
this is a literal block
....
----

....
this is a literal block
....

== Listing Block

Listing blocks are converted using the "noformat" macro.


[listing]
....
.Title of the listing block
----
this is a listing block
----
....

.Title of the listing block
----
this is a listing block
----

== Source Block

Source blocks are converted using the "code" macro. Only languages supported by the Code Block Macro can be used:
`actionscript3`, `applescript`, `bash`, `c#`, `cpp`, `css`, `coldfusion`, `delphi`, `diff`, `erl`, `groovy`,
`xml`, `java`, `jfx`, `js`, `php`, `perl`, `text`, `powershell`, `py`, `ruby`, `sql`, `sass`, `scala`,
`vb`, `yml` (since Confluence 6.7 only)

[listing]
....
[source,java]
----
public class MyCode {
    // comment
}
----
....

[source,java]
----
public class MyCode {
    // comment
}
----


== Source Blocks from External Files (Full Content)

Including source code from external files is supported:

[listing]
....
[source,java]
----
\include::../files/Source.java[]
----
....

[source,java]
----
include::../files/Source.java[]
----


== Source Blocks from External Files (Partial Content)

Restricting the source code to be included based on tags is supported:

[listing]
....
[source,java]
----
\include::../files/SourceWithMethodTag.java[tags=myMethod]
----
....

[source,java]
----
include::../files/SourceWithMethodTag.java[tags=myMethod]
----

[WARNING]
====
Other advanced features like listing file names or callouts are not supported.
====
