= Listings

AsciiDoc literal blocks, listing blocks and code blocks are converted to formatted blocks in Confluence.

A title can be set for each type of block. The title is rendered as the title of the Confluence panel.

== Literal Block

Literal blocks are converted as pre-formatted text.

----
....
this is a literal block
....
----

....
this is a literal block
....

== Listing Block

Listing blocks are converted using the "noformat" macro.


[listing]
....
.Title of the listing block
----
this is a listing block
----
....

.Title of the listing block
----
this is a listing block
----

== Source Block

Source blocks are converted using the "code" macro. Only languages supported by the Code Block Macro can be used:
`actionscript3`, `applescript`, `bash`, `c#`, `cpp`, `css`, `coldfusion`, `delphi`, `diff`, `erl`, `groovy`,
`xml`, `java`, `jfx`, `js`, `php`, `perl`, `text`, `powershell`, `py`, `ruby`, `sql`, `sass`, `scala`,
`vb`, `yml` (since Confluence 6.7 only)

[listing]
....
[source,java]
----
public class MyCode {
    // comment
}
----
....

[source,java]
----
public class MyCode {
    // comment
}
----


== Source Blocks from External Files (Full Content)

Including source code from external files is supported:

[listing]
....
[source,java]
----
\include::../files/Source.java[]
----
....

[source,java]
----
include::../files/Source.java[]
----


== Source Blocks from External Files (Partial Content)

Restricting the source code to be included based on tags is supported:

[listing]
....
[source,java]
----
\include::../files/SourceWithMethodTag.java[tags=myMethod]
----
....

[source,java]
----
include::../files/SourceWithMethodTag.java[tags=myMethod]
----

== Line Numbers

Line numbers for source code blocks can be enabled either using the `:source-linenums-option:` attribute globally for
all source blocks on the page, or per source block using the `linenums` option:

[listing]
....
[source,java,linenums]
----
public class MyCode {
    // comment
}
----
....

[source,java,linenums]
----
public class MyCode {
    // comment
}
----

In case no source language is specified for the source block, line numbers have to be enabled using `[source%linenums]` (not `[source,linenums]`):

[listing]
....
[source%linenums]
----
line one
line two
line three
----
....

[source%linenums]
----
line one
line two
line three
----

A custom start line number for a source block can be specified using the `start` option:

[listing]
....
[source,java,linenums,start=4]
----
public class MyCode {
    // comment
}
----
....

[source,java,linenums,start=4]
----
public class MyCode {
    // comment
}
----


== Source Highlighting

AsciiDoc source highlighters (e.g. CodeRay) are not supported, in favor of using the source highlighting
support of Confluence. Thus, any configured AsciiDoc source highlighter is automatically disabled when publishing to
Confluence.


[WARNING]
====
Other advanced features like listing file names or callouts are not supported.
====
