= Additional Features

== Collapsible Example Blocks

AsciiDoc collapsible example blocks are translated to Confluence with help of the expand macro.

[listing]
....
[%collapsible]
====
This content is revealed when the label is clicked.
====
....

[%collapsible]
====
This content is revealed when the label is clicked.
====


An optional block title can be specified:

[listing]
....
.Toggle Me
[%collapsible]
====
This content is revealed when the "Toggle Me" label is clicked.
====
....

.Toggle Me
[%collapsible]
====
This content is revealed when the "Toggle Me" label is clicked.
====

[NOTE]
====
Non-collapsible example blocks are currently converted to a tip admonition, since Confluence does not provide any
specified example element.
====

[NOTE]
====
Using the `open` option on collapsible expand blocks is currently not supported.
====

== Checklists

Asciidoc's checklists are converted to Confluence task lists pretty natively with one limitation - non checklist items are
converted to incomplete task.

The reason is that Confluence don't support mixed list, so all items are either completed or incompleted task,
while Asciidoc has reacher semantics and element in checklist can be a simple item that is not rendered
as checked on unchecked.

----

- [ ] unchecked item
- [x] checked item
- non checkbox item, but in Confluence it's unchecked task
- [x] mixed content is also supported

 some literal block

----

- [ ] unchecked task
- [x] checked task
- non checkbox item, but in Confluence it's unchecked task
- [x] mixed content is also supported

 some literal block
