= Additional Features

== Footnotes

Although footnotes is not a native construct in Confluence, they are supported and rendered as close as possible to
default asciidoc html layout{_}footnote:[Although due to specifics of confluence links it looks more clumsy in edit mode
and may produce some small visible space after the square brackets].

[listing]
....
My sentence.footnote:[With footnote]
....

My sentence.footnote:[With footnote]

As with regular asciidoc, footnotes can be turned off by defining `:nofootnotes:` attribute

== Collapsible Example Blocks

AsciiDoc collapsible example blocks are translated to Confluence with help of the expand macro.

[listing]
....
[%collapsible]
====
This content is revealed when the label is clicked.
====
....

[%collapsible]
====
This content is revealed when the label is clicked.
====


An optional block title can be specified:

[listing]
....
.Toggle Me
[%collapsible]
====
This content is revealed when the "Toggle Me" label is clicked.
====
....

.Toggle Me
[%collapsible]
====
This content is revealed when the "Toggle Me" label is clicked.
====

[NOTE]
====
Non-collapsible example blocks are currently converted to a tip admonition, since Confluence does not provide any
specified example element.
====

[NOTE]
====
Using the `open` option on collapsible expand blocks is currently not supported.
====
