= Additional Features

== Collapsible Example Blocks

AsciiDoc collapsible example blocks are translated to Confluence with help of the expand macro.

[listing]
....
[%collapsible]
====
This content is revealed when the label is clicked.
====
....

[%collapsible]
====
This content is revealed when the label is clicked.
====


An optional block title can be specified:

[listing]
....
.Toggle Me
[%collapsible]
====
This content is revealed when the "Toggle Me" label is clicked.
====
....

.Toggle Me
[%collapsible]
====
This content is revealed when the "Toggle Me" label is clicked.
====

[NOTE]
====
Non-collapsible example blocks are currently converted to a tip admonition, since Confluence does not provide any
specified example element.
====

[NOTE]
====
Using the `open` option on collapsible expand blocks is currently not supported.
====


== Source File Information

The Confluence Publisher automatically exposes information about the source AsciiDoc file being processed through built-in attributes. These attributes can be used in your AsciiDoc content to reference information about the current file:

[cols="1,3,2"]
|===
|Attribute |Description |Example Value

|`cp-source-path`
|The relative path of the source file from the base directory
|`pages/user-guide.adoc`

|`cp-source-file`
|The filename of the source file including extension
|`user-guide.adoc`

|`cp-source-name`
|The filename of the source file without extension
|`user-guide`
|===

=== Usage Examples

==== Display Source File Name in Content

[listing]
....
This page was generated from: {cp-source-file}
....

This page was generated from: {cp-source-file}

==== Use File Name in Document Title

[listing]
....
= {cp-source-name} Documentation
....

= {cp-source-name} Documentation

==== Reference Source File Path

[listing]
....
Source file location: `{cp-source-path}`
....

Source file location: `{cp-source-path}`
