= Confluence Publisher

_Version {confluencePublisherVersion}_

The Confluence Publisher allows documentation written in AsciiDoc and versioned directly with the documented code base
to be published to a Confluence space. It converts the resulting AsciiDoc HTML output to XHTML compatible with
Confluence, manages included resources as Confluence attachments and ensures that only content modified since the last
publication is again re-published.

[NOTE]
====
The Confluence Publisher has been tested with Confluence 6.0.5
====


== Supported Features

Currently, the Confluence Publisher supports the following AsciiDoc features:

* <<00-index/01-pages.adoc#, Pages>>
* <<00-index/02-includes.adoc#, Includes>>
* <<00-index/03-sections.adoc#, Sections>>
* <<00-index/04-paragraphs.adoc#, Paragraphs>>
* <<00-index/05-tables.adoc#, Tables>>
* <<00-index/06-images.adoc#, Images>>
* <<00-index/07-listings.adoc#, Listings>>
* <<00-index/08-admonitions.adoc#, Admonitions>>
* <<00-index/09-external-links.adoc#, External Links>>
* <<00-index/10-plantuml.adoc#, PlantUML>>
* <<00-index/11-attachments.adoc#, Attachments>>
* <<00-index/12-table-of-contents.adoc#, Table of Contents>>

The Confluence Publisher uses AsciidoctorJ and therefore supports documentation written using the Asciidoctor syntax.
See link:http://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual] for more information about Asciidoctor.


== Documentation Source Structure

The Confluence Publisher expects the AsciiDoc sources to be stored in a specific source structure. This source structure
is used to derive the page hierarchy in Confluence.

----
<root>
 +- top-level-page.adoc    // top-level page AsciiDoc file
 +- top-level-page         // folder for sub-pages and resources of top-level page
    +- sub-page-one.adoc   // first sub page AsciiDoc file
    +- sub-page-two.adoc   // second sub page AsciiDoc file
    +- sub-page-two        // folder for sub-pages and resources of sub-page-two
  +- any-other-folder      // folder for additional files (e.g. images, PlantUML files, ...)
    +- ...
----

AsciiDoc files are expected to be encoded in UTF-8, unless explicitly configured to a different encoding. Resources like
images, PlantUML files, other attachment types and include files can be placed in any location and are resolved relative
to the location of the referencing AsciiDoc file. See <<00-index/02-includes.adoc#, Includes>>,
<<00-index/06-images.adoc#, Images>> and <<00-index/10-plantuml.adoc#, PlantUML>> for more information about resource
file path resolution.

[NOTE]
====
Currently, the ordering of child pages cannot be influenced due to missing support in the Confluence REST API (see
https://jira.atlassian.com/browse/CRA-1276 for information and voting)
====


== Maven Plugin Configuration

The Confluence Publisher is configured with the help of a Maven plugin. A typical configuration could look like this:

[source,xml]
.pom.xml
----
<build>
  <plugins>
    <plugin>
      <groupId>org.sahli.asciidoc.confluence.publisher</groupId>
      <artifactId>asciidoc-confluence-publisher-maven-plugin</artifactId>
      <version><!-- insert version here --></version>
      <configuration>
        <asciidocRootFolder>etc/docs</asciidocRootFolder>
        <sourceEncoding>UTF-8<sourceEncoding> <!-- default -->
        <rootConfluenceUrl>http://localhost:8090</rootConfluenceUrl>
        <skipSslVerification>false</skipSslVerification>
        <spaceKey>SPACE</spaceKey>
        <ancestorId>327706</ancestorId>
        <username>username</username> <!-- or read from property -->
        <password>password</password> <!-- or read from property -->
        <pageTitlePrefix xml:space="preserve">Doc :: </pageTitlePrefix>
        <pageTitleSuffix xml:space="preserve"> [${project.version}]</pageTitleSuffix>
        <versionMessage>Version ${project.version}</versionMessage>
        <attributes>
            <version>${project.version}</version>
            <someOtherKey>value</someOtherKey>
        </attributes>
      </configuration>
    </plugin>
  </plugins>
</build>
----

|===
| Configuration Property | Description | Constraint

| asciidocRootFolder
| The documentation root folder with the AsciiDoc file structure.
| mandatory

| sourceEncoding
| The encoding of the AsciiDoc files.
| optional (defaults to UTF-8)

| rootConfluenceUrl
| The root URL of the Confluence instance to publish to.
  +
  +
  _Note:_ when publishing to Confluence Cloud, the root URL is https://<project>.atlassian.net/wiki.
| mandatory

| skipSslVerification
| Defines whether to disable SSL certificate verification when connecting to Confluence via HTTPS while using self-
  signed certificates.
| optional (defaults to `false`)

| spaceKey
| The key of the Confluence space to publish to.
| mandatory

| ancestorId
| The id of the ancestor page under which the pages are appended.

  Be aware that publishing will remove all pages under the configured ancestor id that are not part of the published
  documentation ("orphaned pages").
| mandatory

| username
| The username of the user to use for publishing.
| mandatory

| password
| The password of the user to use for publishing.
  +
  +
  _Note:_ when publishing to Confluence Cloud, an API token generated via the corresponding Atlassian account has to
  be used as password.
| mandatory

| publishingStrategy
a| The strategy to use when publishing to confluence. Possible values:

* `APPEND_TO_ANCESTOR`: append the published pages to the ancestor and remove all orphaned pages
* `REPLACE_ANCESTOR`: replace the title and the content of the ancestor with those of the one single root page and
remove all orphaned pages (requires the documentation source structure to contain exactly one single root page)

| optional (defaults to `APPEND_TO_ANCESTOR`)

| versionMessage
| The message that will be published with the changes into `Page History` comment.

  Note: Confluence only supports version messages for updated pages, but not when creating new pages.
| optional (defaults to empty)

| attributes| User-defined attributes passed to AsciidoctorJ for replacing corresponding attribute placeholders.
  +
  +
  _Note:_ when using Docker-based publishing, user attributes have to be provided as JSON object structure.
  +
  _Note:_ user attributes are currently not supported for use in the page title.
| optional (default to empty)

| pageTitlePrefix
| The prefix to be prepended to every page title.
  +
  +
  _Note:_ in order to preserve leading or trailing spaces in the page title prefix, the attribute `xml:space="preserve"`
  has to be added to the `pageTitlePrefix` element.
| optional (defaults to empty)

| pageTitleSuffix
| The suffix to be appended to every page title.
  +
  +
  _Note:_ in order to preserve leading or trailing spaces in the page title suffix, the attribute `xml:space="preserve"`
  has to be added to the `pageTitleSuffix` element.
| optional (defaults to empty)

| skip
| Defines whether the plugin execution should be skipped.
| optional (defaults to `false`, only supported for Maven plugin)

| proxyScheme
| The scheme (http or https) used to connect to a forward proxy (in case a forward proxy is required to access the
  Confluence instance).
| optional (defaults to empty)

| proxyHost
| The host of the forward proxy.
| optional (defaults to empty)

| proxyPort
| The port of the forward proxy.
| optional (defaults to empty)

| proxyUsername
| The username of the forward proxy (in case the forward proxy requires basic authentication).
| optional (defaults to empty)

| proxyPassword
| The password of the forward proxy (in case the forward proxy requires basic authentication).
| optional (defaults to empty)
|===

As usually with Maven, configuration properties can either be defined directly in the Confluence Publisher maven plugin
configuration, defined as separate Maven properties, read from the `settings.xml` or passed as system properties with
help of `-D` prefix when invoking Maven.


== Maven Plugin Execution

The Confluence Publisher Maven plugin goal `publish` can be bound to a specific lifecycle, if it should be executed
automatically when building the project, e.g. for execution during the `site` phase:

[source,xml]
----
<!-- ... -->
<executions>
    <execution>
        <id>publish-documentation</id>
        <goals>
            <goal>publish</goal>
        </goals>
        <phase>site</phase>
    </execution>
</executions>
<!-- ... -->
----

Alternatively, the Confluence Publisher Maven plugin can also be executed manually via the command line:

----
mvn org.sahli.asciidoc.confluence.publisher:asciidoc-confluence-publisher-maven-plugin:publish
----


== Using Snapshot Version

The code on master is automatically published as version `0.0.0-SNAPSHOT` to the Sonatype Maven snapshot repository. Use
the following configuration in your `pom.xml` in order to use the latest snapshot version:

[source,xml]
----
<pluginRepository>
  <id>sonatype-snapshot-repo</id>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
  <releases>
    <enabled>false</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</pluginRepository>

<!-- ... -->

<build>
  <plugins>
    <plugin>
      <groupId>org.sahli.asciidoc.confluence.publisher</groupId>
      <artifactId>asciidoc-confluence-publisher-maven-plugin</artifactId>
      <version>0.0.0-SNAPSHOT</version>
      <!-- ... -->
    </plugin>
  </plugins>
</build>
----

== Docker Image

The Confluence Publisher supports publishing documentation via the `confluencepublisher/confluence-publisher` Docker
image. The Docker image does not provide a `latest` tag, but uses the Confluence Publisher version number as the tag.
The Docker image for the code on master is automatically published as version `0.0.0-SNAPSHOT` to Docker Hub.

Instead of providing the `asciidocRootFolder` configuration property as with the Maven plugin, the AsciiDoc sources
have to be mounted to the `/var/asciidoc-root-folder` volume.

In case your documentation sources are already available under a different path in your Docker container, you can
specify the path to the documentation sources via the environment variable `ASCIIDOC_ROOT_FOLDER`.

All other mandatory and optional configuration properties from the Maven plugin have to be / can be specified as
environment variable in all-uppercase writing, e.g. `ROOT_CONFLUENCE_URL` for `rootConfluenceUrl`.

[NOTE]
====
When specifying the `ROOT_CONFLUENCE_URL` environment variable, be sure to provide the host as it is resolvable from
within the Docker container.
====

The following command shows an example for publishing AsciiDoc sources via the Confluence Publisher Docker image:

----
docker run --rm -e ROOT_CONFLUENCE_URL=http://confluence-host \
   -e SKIP_SSL_VERIFICATION=false \
   -e USERNAME=username \
   -e PASSWORD=1234 \
   -e SPACE_KEY=XYZ \
   -e ANCESTOR_ID=012345 \
   -e PAGE_TITLE_PREFIX="Draft - " \
   -e PAGE_TITLE_SUFFIX=" (V 1.0)" \
   -e PUBLISHING_STRATEGY=REPLACE_ANCESTOR \
   -e VERSION_MESSAGE="V 1.0" \
   -e ATTRIBUTES='{"attribute1": "value1", "attribute2": "value2"}' \
   -e PROXY_SCHEME=https \
   -e PROXY_HOST=my.proxy.com \
   -e PROXY_PORT=8443 \
   -v /absolute/path/to/asciidoc-root-folder:/var/asciidoc-root-folder \
   confluencepublisher/confluence-publisher:0.0.0-SNAPSHOT
----

In case you want to extend the Confluence Publisher Docker image or if you use it as part of your CI build, you
should use the script `publish.sh` for triggering the actual publishing. The following shows an example for a
GitLab CI build step that uses the Confluence Publisher Docker image as its execution environment, assuming the
documentation sources already being available in `./docs/` from the project checkout:

----
publish-docs:
  stage: publish-docs
  image:
    name: confluencepublisher/confluence-publisher:0.0.0-SNAPSHOT
    entrypoint: [""]
  variables:
    ASCIIDOC_ROOT_FOLDER: ./docs/
    ROOT_CONFLUENCE_URL: http://confluence-host
    ...
  script:
    - publish.sh
----
