= Confluence Publisher

The Confluence Publisher allows documentation written in AsciiDoc and versioned directly with the documented code base
to be published to a Confluence space. It converts the resulting AsciiDoc HTML output to XHTML compatible with
Confluence, manages included resources as Confluence attachments and ensures that only content modified since the last
publication is again re-published.

[NOTE]
====
The Confluence Publisher has been tested with Confluence 6.0.5
====


== Supported Features

Currently, the Confluence Publisher supports the following AsciiDoc features:

* <<00-index/01-pages.adoc#, Pages>>
* <<00-index/02-includes.adoc#, Includes>>
* <<00-index/03-sections.adoc#, Sections>>
* <<00-index/04-paragraphs.adoc#, Paragraphs>>
* <<00-index/05-tables.adoc#, Tables>>
* <<00-index/06-images.adoc#, Images>>
* <<00-index/07-listings.adoc#, Listings>>
* <<00-index/08-admonitions.adoc#, Admonitions>>
* <<00-index/09-external-links.adoc#, External Links>>
* <<00-index/10-plantuml.adoc#, PlantUML>>
* <<00-index/11-attachments.adoc#, Attachments>>

The Confluence Publisher uses AsciidoctorJ and therefore supports documentation written using the Asciidoctor syntax.
See link:http://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual] for more information about Asciidoctor.


== Documentation Source Structure

The Confluence Publisher expects the AsciiDoc sources to be stored in a specific source structure. This source structure
is used to derive the page hierarchy in Confluence.

----
<root>
 +- top-level-page.adoc    // top-level page AsciiDoc file
 +- top-level-page         // folder for sub-pages and resources of top-level page
    +- sub-page-one.adoc   // first sub page AsciiDoc file
    +- sub-page-two.adoc   // second sub page AsciiDoc file
    +- sub-page-two        // folder for sub-pages and resources of sub-page-two
  +- any-other-folder      // folder for additional files (e.g. images, PlantUML files, ...)
    +- ...
----

AsciiDoc files are expected to be encoded in UTF-8. Resources like images, PlantUML files, other attachment types and
include files can be placed in any location within the documentation root folder. See
<<00-index/02-includes.adoc#, Includes>>, <<00-index/06-images.adoc#, Images>> and
<<00-index/10-plantuml.adoc#, PlantUML>> for more information about resource file path resolution.

[NOTE]
====
Currently, the ordering of child pages cannot be influenced due to missing support in the Confluence REST API (see
https://jira.atlassian.com/browse/CRA-1276 for information and voting)
====


== Maven Plugin Configuration

The Confluence Publisher is configured with the help of a Maven plugin. A typical configuration could look like this:

[source,xml]
.pom.xml
----
<build>
  <plugins>
    <plugin>
      <groupId>org.sahli.asciidoc.confluence.publisher</groupId>
      <artifactId>asciidoc-confluence-publisher-maven-plugin</artifactId>
      <version><!-- insert version here --></version>
      <configuration>
        <asciidocRootFolder>etc/docs</asciidocRootFolder>
        <rootConfluenceUrl>http://localhost:8090</rootConfluenceUrl>
        <spaceKey>SPACE</spaceKey>
        <ancestorId>327706</ancestorId>
        <username>username</username> <!-- or read from property -->
        <password>password</password> <!-- or read from property -->
      </configuration>
    </plugin>
  </plugins>
</build>
----

|===
| Configuration Property | Description

| asciidocRootFolder
| The documentation root folder with the AsciiDoc file structure.

| rootConfluenceUrl
| The root URL of the Confluence instance to publish to.

| spaceKey
| The key of the Confluence space to publish to.

| ancestorId
| The id of the ancestor page under which the pages are appended.

  Use `SPACE_ROOT` to publish to the space root directly. Be aware that publishing to the space root directly will
  remove all pages that are not part of the published documentation.

| username
| The username of the user to use for publishing.

| password
| The password of the user to use for publishing.
|===

As usually with Maven, configuration properties can either be defined directly in the Confluence Publisher maven plugin
configuration, defined as separate Maven properties, read from the `settings.xml` or passed as system properties with
help of `-D` prefix when invoking Maven.

== Maven Plugin Execution

The Confluence Publisher Maven plugin goal `publish` can be bound to a specific lifecycle, if it should be executed
automatically when building the project, e.g. for execution during the `site` phase:

----
<!-- ... -->
<executions>
    <execution>
        <id>publish-documentation</id>
        <goals>
            <goal>publish</goal>
        </goals>
        <phase>site</phase>
    </execution>
</executions>
<!-- ... -->
----

Alternatively, the Confluence Publisher Maven plugin can also be executed manually via the command line:

----
mvn org.sahli.asciidoc.confluence.publisher:asciidoc-confluence-publisher-maven-plugin:publish
----
