= Confluence Publisher Documentation

The Confluence Publisher allows documentation written in AsciiDoc and versioned directly with the documented code base
to be published to a Confluence space. It converts the resulting AsciiDoc HTML output to XHTML compatible with
Confluence, manages included resources as Confluence attachments and ensures that only content modified since the last
publication is again re-published.

[NOTE]
====
The Confluence Publisher has been tested with Confluence 6.0.5
====

Currently, the Confluence Publisher supports the following AsciiDoc features:

* <<00_index/01_pages.adoc#, Pages>>
* <<00_index/02_includes.adoc#, Includes>>
* <<00_index/03_sections.adoc#, Sections>>
* <<00_index/04_paragraphs.adoc#, Paragraphs>>
* <<00_index/05_tables.adoc#, Tables>>
* <<00_index/06_images.adoc#, Images>>
* <<00_index/07_listings.adoc#, Listings>>
* <<00_index/08_admonitions.adoc#, Admonitions>>
* <<00_index/09_external_links.adoc#, External Links>>
* <<00_index/10_plantuml.adoc#, PlantUML>>

== To Document
* reference to official AsciiDoc documentation (or AsciiDoctor ?)
* documentation content root
* Confluence page tree structure (maybe improve based on file ordering)
* Maven plugin configuration
